### PR TITLE
Added custom instruments

### PR DESCRIPTION
**Pull request by karl-police**
Adds custom instruments support.

Even though playSound only allows to play one sound. Uhh well...

It's better than nothing and does not cause any issues from what I tested.

### CODE REVIEW

**Comment by bjm021** [comment]
Do you have an example of custom instruments that I can try locally?

**Comment by karl-police** [comment]
> Do you have an example of custom instruments that I can try locally?

I had one. OpenNBS comes with custom sounds by default

the way on how this works though is that OpenNBS doesn't actually have a way to determine the actual sound name of the custom sound

you have to name the sound so that it works with ``playsound`` as e.g.

image

in the code's example

it's using the "Name" as the sound name

if the sound doesn't exist I don't think it even plays it nor throws an error. If you'd have been playing it through the speaker playNote, it would say invalid instrument

&nbsp;

To test this properly, I added at least 2 custom sounds.

OpenNBS automatically names it when you select the first sound for the custom instrument. But then you have to re-name it manually.

**Comment by bjm021** [comment]
Well that sounds compelling, I'll take your word on this one since I don't have much time at the moment and since it doesn't break existing code I'll approve it.

**Comment by bjm021** [comment]
Oops, wrong button 😅

**Comment by bjm021** [comment]
I'll update the pastebin right away!

**Pull request merged**
